baseURL = "https://porcow.github.io/"
languageCode = "zh-cn"
title = "Nil's Void"
theme = "PaperMod"

[params]
  author = "Nil Void"
  ShowReadingTime = true
  ShowToc = true
  defaultTheme = "auto"
  comments = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPageNums = true
  [[params.homeInfoParams]]
    Title = "ğŸ‘¨â€ğŸ’» Coding | ğŸ“— Reading | ğŸ‘¾ Gaming"
    Content = """
    ğŸ‘‹ Hi, Welcome to Nil's Void!
    """
  [[params.socialIcons]]
    name = "github"
    title = "Github"
    url = "https://github.com/porcow"
  [[params.socialIcons]]
    name = "KoFi"
    title = "Buy me a Ko-Fi :)"
    url = "https://ko-fi.com/nilsvoid"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Games"
    url = "/games/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"] # necessary for search
    

[caches]
  [caches.images]
    dir = ':cacheDir/images'
